client_config_backend: settings
client_config:
  client_id: 11296313410-qrm12cuqeb4jnsgg0lj55mjac9l2prbr.apps.googleusercontent.com
  client_secret: LoIJoFIp20W7Au8CIMTbMGhK

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.file
  - https://www.googleapis.com/auth/drive.install
